/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto1;


import java.awt.Image;
import java.sql.Statement;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author lenovo
 */
public class Interface extends javax.swing.JFrame {
    String filename = null;
    byte [] pimage = null;
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        show_user();
        this.setLocationRelativeTo(null);
        
    }
            Connection con1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtTurma = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtCaminhodaFoto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "Turma", "Matricula", "Foto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Byte.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 420, 310));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 210, -1));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 210, -1));

        jLabel2.setText("Nome");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jLabel3.setText("Turma");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));
        jPanel1.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 210, -1));

        jLabel4.setText("Matricula");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        lblFoto.setBackground(new java.awt.Color(255, 255, 255));
        lblFoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFoto.setText("     Inserir imagem");
        lblFoto.setToolTipText("");
        lblFoto.setAlignmentX(2.0F);
        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 137, 176));

        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        jButton3.setText("Deletar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jButton4.setText("AddImage");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        jPanel1.add(txtCaminhodaFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 290, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 430, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    PreparedStatement insert;

    public ArrayList<Aluno> userList(){
        ArrayList<Aluno> userList = new ArrayList<>();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            String url = "jdbc:mysql://localhost:3306/escola";
            String usuario = "root";
            String senha = "";
            
            Connection  con = DriverManager.getConnection(url,usuario,senha);
            String query1= "Select * From aluno";
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery(query1);
            Aluno aluno;
            while(rs.next()){
                aluno=new Aluno(rs.getInt("id"),rs.getInt("Matricula"),rs.getString("Nome"),rs.getString("Turma"),rs.getBytes("foto"));
                userList.add(aluno);
                
            }
            
        } catch (Exception e) {
        }
        return userList;
    }
    public void show_user(){
        ArrayList<Aluno> list = userList();
        DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
        Object[] row = new Object[4];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getId();
            row[1]=list.get(i).getNome();
            row[2]=list.get(i).getTurma();
            row[3]=list.get(i).getMatricula();
            Df.addRow(row);
            
        }
    }


    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
               Connection conexao = null;
        String url = "jdbc:mysql://localhost:3306/escola";
        String usuario = "root";
        String senha = "";
    
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conexao = DriverManager.getConnection(url, usuario, senha);
            
            String sql ="INSERT INTO aluno (nome, matricula, turma, foto) VALUES (?, ?, ?, ?)";
            PreparedStatement atmt = conexao.prepareStatement(sql);
            atmt.setString(1, txtNome.getText());
            atmt.setLong(2, Integer.parseInt(txtMatricula.getText()));
            atmt.setString(3, txtTurma.getText());
            atmt.setBytes(4, pimage);
            
            atmt.executeUpdate();
            show_user();
            atmt.close();
            conexao.close();
                    
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
        
        JOptionPane.showMessageDialog(this, "Aluno Criado");
        
        txtNome.setText("");
        txtTurma.setText("");
        txtMatricula.setText("");
        lblFoto.setIcon(null);
        txtNome.requestFocus();
            

        

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
      
        DefaultTableModel Df =(DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        txtNome.setText(Df.getValueAt(selectedIndex, 1).toString());
        txtTurma.setText(Df.getValueAt(selectedIndex, 2).toString());
        txtMatricula.setText(Df.getValueAt(selectedIndex, 3).toString());
        
        byte[] img = (userList().get(selectedIndex).getFoto());    
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_SMOOTH));
        lblFoto.setIcon(imageIcon);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/escola";
            String usuario = "root";
            String senha = "";
            
            Connection conexao = DriverManager.getConnection(url, usuario, senha);
            int row = jTable1.getSelectedRow();
            String value = (jTable1.getModel().getValueAt(row, 0).toString());
            
            String sql ="UPDATE aluno set nome= ? , matricula= ? , turma= ? , foto= ? where id="+value;
            PreparedStatement atmt = conexao.prepareStatement(sql);
            atmt.setString(1, txtNome.getText());
            atmt.setLong(2, Integer.parseInt(txtMatricula.getText()));
            atmt.setString(3, txtTurma.getText());
            atmt.setBytes(4, pimage);
            
            atmt.executeUpdate();
            DefaultTableModel Df =(DefaultTableModel) jTable1.getModel();
            Df.setRowCount(0);
            
            show_user();
            atmt.close();
            conexao.close();
                    
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
        
        JOptionPane.showMessageDialog(this, "Aluno Criado");
        
        txtNome.setText("");
        txtTurma.setText("");
        txtMatricula.setText("");
        lblFoto.setIcon(null);
        txtNome.requestFocus();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/escola";
            String usuario = "root";
            String senha = "";
            
            Connection conexao = DriverManager.getConnection(url, usuario, senha);
            int row = jTable1.getSelectedRow();
            String value = (jTable1.getModel().getValueAt(row, 0).toString());
            
            String sql ="Delete From aluno where id="+value;
            PreparedStatement atmt = conexao.prepareStatement(sql);
            
            atmt.executeUpdate();
            DefaultTableModel Df =(DefaultTableModel) jTable1.getModel();
            Df.setRowCount(0);
            
            show_user();
            atmt.close();
            conexao.close();
                    
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
        
        JOptionPane.showMessageDialog(this, "Aluno Criado");
        
        txtNome.setText("");
        txtTurma.setText("");
        txtMatricula.setText("");
        lblFoto.setIcon(null);
        txtNome.requestFocus();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       
           JFileChooser chooser =  new JFileChooser(); 
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_SMOOTH));
        lblFoto.setIcon(imageIcon);
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image); 
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte [] buf = new byte[1024];
            for(int readNum;(readNum = fis.read(buf))!=-1;){
                bos.write(buf,0,readNum);
        }
          
            pimage= bos.toByteArray();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
        

        
    }//GEN-LAST:event_jButton4ActionPerformed
        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTextField txtCaminhodaFoto;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTurma;
    // End of variables declaration//GEN-END:variables
}
